### ISSUE TITLE
Deprecated Alias Warning

### ISSUE THREAD

**Issue by Daverover66** [tcarwash/home-assistant_noaa-space-weather#64]
2.0.1

## Configuration

```yaml
Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 07:23:59 (1 occurrences)
Last logged: 07:23:59

Config was used from noaa_space_weather, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'noaa_space_weather' custom integration
```

## Debug log

```text

Add your logs here.

```
